const this_path = 'WALLET_'

export const RESET_STORE = `${this_path}RESET_STORE`,
  AMOUNT_PRESET_STEP = `${this_path}AMOUNT_PRESET_STEP`,
  AMOUNT_PRESET = `${this_path}AMOUNT_PRESET`,
  CHANGE_BALANCE = `${this_path}CHANGE_BALANCE`,
  CHANGE_AUCTION_MEMBERSHIP = `${this_path}CHANGE_AUCTION_MEMBERSHIP`,
  CHANGE_AUCTION_MEMBERSHIP_INFO = `${this_path}CHANGE_AUCTION_MEMBERSHIP_INFO`
